# Generated by Django 6.0.6 on 2026-06-06 11:12

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text="Original filename from the user's computer", max_length=255)),
                ('file', models.FileField(help_text='The PDF file, stored in media/resumes/', upload_to=api.models.resume_upload_path)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created. auto_now_add=True means Django sets this automatically.')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
