# Generated by Django 6.0.6 on 2026-06-08 09:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='analysis',
            field=models.JSONField(blank=True, help_text='The full AI analysis result stored as JSON. JSONField stores any Python dict/list natively in SQLite. null=True means the column can be empty before analysis runs.', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='analysis_error',
            field=models.TextField(blank=True, help_text='Error message if analysis failed — helps with debugging', null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Tracks where this resume is in the analysis pipeline', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, help_text='When the AI analysis completed', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=api.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file_size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
