# Generated by Django 6.0.6 on 2026-06-08 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resume_analysis_resume_analysis_error_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='resume',
            name='analysis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='analysis_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(help_text='Raw job posting text pasted by the user')),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('matching', 'Matching'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('match_result', models.JSONField(blank=True, help_text='Full AI match report stored as JSON', null=True)),
                ('match_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('resume', models.ForeignKey(help_text='The resume this match is against', on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='api.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
